---

port: 4000
host: 0.0.0.0
safe: false


### site serving configuration ###
exclude: [CNAME, README.md, .gitignore]
permalink: /:title ## disables post output
timezone: null
lsi: false
markdown: kramdown


### content configuration ###
title:       "Doritool - Website"
keywords:    "Doritool, bioinformatic"
description: "Doritool: A bioinformatic pipeline"
source_link_doritool: "https://github.com/doritool/doritool"
source_link_web: "https://github.com/doritool/doritool.github.io"
form_link: "https://goo.gl/forms/M2bbiRFgprJxD8Ap2"
favicon:     "img/favicon.ico"
#touch_icon:  "img/apple-touch-icon.png"
#google_analytics_key: UA-49607422-1 ## put YOUR key here to enable tracking! (blank to disable)


### template colors, used site-wide via css ###
colors:
  black:     '#111111'
  white:     '#ffffff'
  blue:      '#0000cc'
  green:     '#00cc00'
  orange:    '#ffb300'
  red:       '#cc0000'
  #purple:    '#c869bf'

kramdown:
  auto_ids:  false

